site_name: 'Notes: Write to Ease Learning'
site_url: 'https://mohammedi-haroune.github.io/notes/'
repo_url: 'https://github.com/mohammedi-haroune/notes'
repo_name: 'Github'
site_description: 'Notes: Writing to ease learning'
site_author: 'MOHAMMEDI Haroune'
google_analytics: ['UA-137032230-1', 'auto']

theme:
  name: 'material'
  font:
    text: 'Montserrat'
    code: 'Source Code Pro'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/mohammedi-haroune'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/users/7573221/haroun-mohammedi'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/mohammedi-haroune-3b3836170'
  search:
    language: ['en']
  disqus: 'notes-6'

plugins:
  - search:
      lang: ['en']

markdown_extensions:
  - codehilite
  - admonition

nav:
- Home: 'index.md'
- High Output Managements:
    - 'Summary': 'high_output_management/SUMMARY.md'
    - 'Introduction': 'high_output_management/introduction.md'
    - 'The Basics of Production Delivering a Breakfast': 'high_output_management/chapter1.md'
    - 'Managing the Breakfast Factory': 'high_output_management/chapter2.md'
    - 'Managerial Leverage': 'high_output_management/chapter3.md'
- Scala:
    - 'Summary': 'scala/SUMMARY.md'
    - 'Scala': 'scala/chapter1.md'
    - 'Sbt': 'scala/sbt.md'
    - 'Ammonite': 'scala/ammonite.md'
- Python:
    - 'Firebase': 'python/firebase.md'
    - 'Flask': 'python/flask.md'
- Configuration:
    - 'Summary': 'configurations/SUMMARY.md'
    - 'Log back': 'configurations/logback.md'
    - 'Docker': 'configurations/docker.md'
    - 'Docker Swarm': 'configurations/swarm.md'
    - 'DomeJudge': 'configurations/domejudge.md'
    - 'Archiva': 'configurations/archiva.md'
    - 'Kafka': 'configurations/kafka.md'
    - 'Google Cloud': 'configurations/gcloud.md'
    - 'Log4j 2': 'configurations/log4j2.md'
- Big Ideas about Startups:
    - 'Summary': 'big_ideas/SUMMARY.md'
    - 'Startups': 'big_ideas/chapter1.md'
- Elasticserach:
    - 'Summary': 'elasticsearch/SUMMARY.md'
    - 'Getting Started': 'elasticsearch/chapter1.md'
- Programming:
    - 'Summary': 'programming/SUMMARY.md'
    - 'Chpater 1': 'programming/chapter1.md'
    - 'Spacemacs': 'programming/spacemacs.md'
- ReactJs:
    - 'Summary': 'react/SUMMARY.md'
    - 'Main Concepts': 'react/main_concepts.md'
